name: Feature request
title: "[Feature] "
description: Request a new capability
labels: ["enhancement"]
body:
    - type: markdown
      attributes:
          value: |
              Thank you for suggesting a new feature!

    - type: checkboxes
      attributes:
          label: Search before asking
          description: >
              Please make sure to search in the [issues](https://github.com/IBM/data-prep-lab/issues) first to see
              whether the same request was reported already.
          options:
              - label: >
                    I searched the [issues](https://github.com/IBM/data-prep-lab/issues) and found no similar issues.
                required: true

    - type: dropdown
      attributes:
          label: Component
          description: |
              What component would implement this new feature.
          multiple: true
          options:
            - Documentation
            - KFP workflows
            - Data Connector
            - Ray Runtime
            - Spark Runtime
            - Python Runtime
            - Notebooks and Recipe
            - Makefiles and CI/CD
            - transforms/code_profiler
            - transforms/code_quality
            - transforms/code2parquet
            - transforms/doc_chunk
            - transforms/doc_id
            - transforms/doc_quality
            - transforms/ededup
            - transforms/extreme_tokenized
            - transforms/fdedup
            - transforms/filter
            - transforms/GneissWeb bloom
            - transforms/gneissweb_classification
            - transforms/hap
            - transforms/header_cleanser
            - transforms/html2parquet
            - transforms/lang_id
            - transforms/license_select
            - transforms/pdf2parquet
            - transforms/pii_redactor
            - transforms/profiler
            - transforms/proglang_select
            - transforms/readability
            - transforms/rep_removal
            - transforms/resize
            - transforms/similarity
            - transforms/text_encoder
            - transforms/tokenization
            - transforms/tokenization2arrow
            - transforms/web2parquet
            - transdforms/Other
            - Other
      validations:
          required: true

    - type: textarea
      attributes:
          label: Feature
          description: Describe the new functionality
          placeholder: >
              Please describe the new capability including its core addition and any special cases that 
              need to be addressed.

              **NOTE**: please copy and paste texts instead of taking screenshots of them for easy future search.
      validations:
          required: true

    - type: checkboxes
      attributes:
          label: Are you willing to submit a PR?
          description: >
              This is absolutely not required, but we are happy to guide you in the contribution process
              especially if you already have a good understanding of how to implement the fix.
          options:
              - label: Yes I am willing to submit a PR!

    - type: markdown
      attributes:
          value: "Thanks for completing our form!"
